### ISSUE TITLE
Script redirects to ipv4.google.com

### ISSUE THREAD

**Issue by dom6770** [FarisHijazi/SuperGoogle#26]
As soon as I activate the script every google page gets redirected from google.com to ipv4.google.com. Clicking on the images tab gives me then the error 404 not found.

`https://www.google.com/search?q=github`
-->
`https://ipv4.google.com/search?q=github`
-->
`https://ipv4.google.com/search?q=github&newwindow=1&sxsrf=ALeKk01G9DNLg12zJi9H4BrwSp6LAzORHA:1587337951325&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjklejVzvXoAhVLxcQBHUAuAs4Q_AUoAXoECCsQAw&biw=2560&bih=1307`

**Comment by FarisHijazi** [comment]
this has been resolved, please update the script and clear all storage from tampermonkey, (make sure advanced settings are enabled to see the storage tab)

another easy way is to just completely remove the script then install it


closing this issue, please reopen if issue persists
